name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: denoland/setup-deno@v1
    - uses: actions/checkout@v2
    - run: deno lint
    - run: deno fmt --check

  test:
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: denoland/setup-deno@v1
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm run --silent test
    - run: npm ci  --ignore-scripts
    - run: npm run --silent prepare
    - run: node/dtest.mjs out/test/*.test.js
